### ISSUE TITLE
Suggestion: add native utility types

### ISSUE THREAD

**Issue by johh** [Gerrit0/typedoc-plugin-mdn-links#3]
Linking to the [utility types](https://www.typescriptlang.org/docs/handbook/utility-types.html) provided by TypeScript would be really handy imho, though it might be outside the scope of this plugin, as we would not link to MDN.

Let me know what you think, I'd be happy to create a PR!

**Comment by Gerrit0** [comment]
I really like this idea, though I agree it doesn't really fit with this plugin... I think this would be a good fit for a new plugin. I'm somewhat tempted to say it should go in typedoc itself, but since nothing else links to external websites (except for the generator link in the footer), it feels more appropriate to delegate to a plugin for now.

**Comment by johh** [comment]
Cool, I'll create a separate plugin and get back to you once it's ready!

**Comment by Gerrit0** [comment]
Ended up deciding to add support for it, under an option which defaults to being on in case someone doesn't like it, but since they're also under the TS package it doesn't seem too weird to have it here.
